services:
  nginx:
    image: nginx:1.24.0-alpine-slim
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./conf_no_cert/:/etc/nginx/conf.d/:ro
      - ../../certbot/www:/var/www/certbot/:ro
      - ../../certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot
    volumes:
      - ../../certbot/www/:/var/www/certbot/:rw
      - ../../certbot/conf/:/etc/nginx/ssl/:rw
