name: Deploy to EC2 and build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::662775645668:role/mischaikow-com-github-access
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1
      - name: EC2 Connect
        run: |
          aws ec2-instance-connect ssh --instance-id i-03c0a5504af2c0cff
      - name: Pull & build repository
        run: | 
          bash build_run_docker.sh
